fixtures:
    symlinks:
      tea:  "#{source_dir}"
      test: "#{source_dir}/spec/fixtures/test"
    repositories:
      stdlib:
        repo: https://github.com/puppetlabs/puppetlabs-stdlib.git
    forge_modules:
